# House Prices: Advanced Regression Techniques

## 1. Getting data with Pandas

In [174]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder

In [175]:
train_data = pd.read_csv('all/train.csv')
test_data  = pd.read_csv('all/test.csv')

In [176]:
train_label = train_data['SalePrice']
train_data_input = train_data.drop('SalePrice',1)
all_data   = pd.concat([train_data_input, test_data], axis=0)

print(train_data.shape)
print(train_data_input.shape)
print(test_data.shape)
print(all_data.shape)

(1460, 81)
(1460, 80)
(1459, 80)
(2919, 80)

In [177]:
train_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

## 2. Data exploration

In [178]:
all_data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Shed,350,11,2009,WD,Normal
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,1,2008,WD,Normal
10,11,20,RL,70.0,11200,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
11,12,60,RL,85.0,11924,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,7,2006,New,Partial
12,13,20,RL,NaN,12968,Pave,NaN,IR2,Lvl,AllPub,...,176,0,NaN,NaN,NaN,0,9,2008,WD,Normal
13,14,20,RL,91.0,10652,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,8,2007,New,Partial
14,15,20,RL,NaN,10920,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,GdWo,NaN,0,5,2008,WD,Normal
15,16,45,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,GdPrv,NaN,0,7,2007,WD,Normal
16,17,20,RL,NaN,11241,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Shed,700,3,2010,WD,Normal
17,18,90,RL,72.0,10791,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,Shed,500,10,2006,WD,Normal
18,19,20,RL,66.0,13695,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2008,WD,Normal
19,20,20,RL,70.0,7560,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,5,2009,COD,Abnorml
20,21,60,RL,101.0,14215,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,New,Partial
21,22,45,RM,57.0,7449,Pave,Grvl,Reg,Bnk,AllPub,...,0,0,NaN,GdPrv,NaN,0,6,2007,WD,Normal
22,23,20,RL,75.0,9742,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
23,24,120,RM,44.0,4224,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2007,WD,Normal
24,25,20,RL,NaN,8246,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,5,2010,WD,Normal
25,26,20,RL,110.0,14230,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,7,2009,WD,Normal
26,27,20,RL,60.0,7200,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal
27,28,20,RL,98.0,11478,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal
28,29,20,RL,47.0,16321,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2006,WD,Normal
29,30,30,RM,60.0,6324,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2008,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,2890,30,RM,50.0,7030,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2006,WD,Normal
1430,2891,50,RM,75.0,9060,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Normal
1431,2892,30,C (all),69.0,12366,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Abnorml
1432,2893,190,C (all),50.0,9000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Abnorml
1433,2894,50,C (all),60.0,8520,Grvl,NaN,Reg,Bnk,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Normal
1434,2895,120,RM,41.0,5748,Pave,NaN,IR1,HLS,AllPub,...,153,0,NaN,NaN,NaN,0,2,2006,New,Partial
1435,2896,120,RM,44.0,3842,Pave,NaN,IR1,HLS,AllPub,...,155,0,NaN,NaN,NaN,0,12,2006,WD,Normal
1436,2897,20,RL,69.0,23580,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Normal
1437,2898,90,RL,65.0,8385,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Normal
1438,2899,20,RL,70.0,9116,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1439,2900,80,RL,140.0,11080,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1440,2901,20,RL,NaN,50102,Pave,NaN,IR1,Low,AllPub,...,138,0,NaN,NaN,NaN,0,3,2006,WD,Alloca
1441,2902,20,RL,NaN,8098,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Normal
1442,2903,20,RL,95.0,13618,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,New,Partial
1443,2904,20,RL,88.0,11577,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,New,Partial
1444,2905,20,NaN,125.0,31250,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1445,2906,90,RM,78.0,7020,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal
1446,2907,160,RM,41.0,2665,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1447,2908,20,RL,58.0,10172,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Normal
1448,2909,90,RL,NaN,11836,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,3,2006,WD,Normal
1449,2910,180,RM,21.0,1470,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Normal
1450,2911,160,RM,21.0,1484,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1451,2912,20,RL,80.0,13384,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1452,2913,160,RM,21.0,1533,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2006,WD,Abnorml
1453,2914,160,RM,21.0,1526,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,GdPrv,NaN,0,6,2006,WD,Normal
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [179]:
train_data['SalePrice'].describe()

count      1460.000000
mean     180921.195890
std       79442.502883
min       34900.000000
25%      129975.000000
50%      163000.000000
75%      214000.000000
max      755000.000000
Name: SalePrice, dtype: float64

## 3. Prepare data

In [180]:
missing_data = all_data.isnull().sum().sort_values(ascending=False)
missing_data = missing_data[missing_data > 0]

In [181]:
count        = all_data.isnull().sum().sort_values(ascending=False)
percent_relt = all_data.isnull().sum() / all_data.isnull().count()
percent_relt = percent_relt.sort_values(ascending=False)*100

missing_data_perc  = pd.concat([count, percent_relt], axis=1, keys = ['Count', 'Percent(%)'])
missing_data_perc.head(50)

              Count  Percent(%)
PoolQC         2909   99.657417
MiscFeature    2814   96.402878
Alley          2721   93.216855
Fence          2348   80.438506
FireplaceQu    1420   48.646797
LotFrontage     486   16.649538
GarageCond      159    5.447071
GarageQual      159    5.447071
GarageYrBlt     159    5.447071
GarageFinish    159    5.447071
GarageType      157    5.378554
BsmtCond         82    2.809181
BsmtExposure     82    2.809181
BsmtQual         81    2.774923
BsmtFinType2     80    2.740665
BsmtFinType1     79    2.706406
MasVnrType       24    0.822199
MasVnrArea       23    0.787941
MSZoning          4    0.137033
BsmtHalfBath      2    0.068517
Utilities         2    0.068517
Functional        2    0.068517
BsmtFullBath      2    0.068517
BsmtFinSF1        1    0.034258
Exterior1st       1    0.034258
Exterior2nd       1    0.034258
BsmtFinSF2        1    0.034258
BsmtUnfSF         1    0.034258
TotalBsmtSF       1    0.034258
SaleType          1    0.034258
Electrical        1    0.034258
KitchenQual       1    0.034258
GarageArea        1    0.034258
GarageCars        1    0.034258
HouseStyle        0    0.000000
LandSlope         0    0.000000
MSSubClass        0    0.000000
LotArea           0    0.000000
Street            0    0.000000
LotShape          0    0.000000
LandContour       0    0.000000
LotConfig         0    0.000000
Neighborhood      0    0.000000
OverallQual       0    0.000000
Condition1        0    0.000000
Condition2        0    0.000000
RoofMatl          0    0.000000
RoofStyle         0    0.000000
BldgType          0    0.000000
YearRemodAdd      0    0.000000

In [182]:
all_data = all_data.drop((missing_data_perc[missing_data_perc['Percent(%)'] > 25]).index, 1)

all_data = all_data.drop('LotArea', 1)
all_data = all_data.drop('YearBuilt', 1)
all_data = all_data.drop('BsmtFinSF1', 1)

In [187]:
all_data['LotFrontage']  = all_data['LotFrontage'].fillna(0)
all_data['GarageCond']   = all_data['GarageCond'].fillna('NA')
all_data['GarageType']   = all_data['GarageType'].fillna('NA')
all_data['GarageFinish'] = all_data['GarageFinish'].fillna('NA')
all_data['GarageQual']   = all_data['GarageQual'].fillna('NA')
all_data['BsmtExposure'] = all_data['BsmtExposure'].fillna('NA')
all_data['BsmtFinType2'] = all_data['BsmtFinType2'].fillna('NA')
all_data['BsmtFinType1'] = all_data['BsmtFinType1'].fillna('NA')
all_data['BsmtCond']     = all_data['BsmtCond'].fillna('NA')
all_data['BsmtQual']     = all_data['BsmtQual'].fillna('NA')
all_data['MasVnrArea']   = all_data['MasVnrArea'].fillna(0)
all_data['MasVnrType']   = all_data['MasVnrType'].fillna('None')
all_data['Electrical']   = all_data['Electrical'].fillna('SBrkr')
all_data['MSZoning']     = all_data['MSZoning'].fillna('RM')
all_data['Functional']   = all_data['Functional'].fillna('Typ')
all_data['BsmtFullBath'] = all_data['BsmtFullBath'].fillna(0)
all_data['BsmtHalfBath'] = all_data['BsmtFullBath'].fillna(0)
all_data['Utilities']    = all_data['Utilities'].fillna('AllPub')
all_data['GarageArea']   = all_data['GarageArea'].fillna(0)
all_data['BsmtFinSF2']   = all_data['BsmtFinSF2'].fillna(0)
all_data['BsmtUnfSF']    = all_data['BsmtUnfSF'].fillna(0)
all_data['SaleType']     = all_data['SaleType'].fillna('Oth')
all_data['Exterior2nd']  = all_data['Exterior2nd'].fillna('Other')
all_data['Exterior1st']  = all_data['Exterior1st'].fillna('Other')
all_data['KitchenQual']  = all_data['KitchenQual'].fillna('TA')
all_data['GarageCars']   = all_data['GarageCars'].fillna(0)
all_data['TotalBsmtSF']  = all_data['TotalBsmtSF'].fillna(0)

In [188]:
all_data['GarageYrBlt'].describe()
all_data['GarageYrBlt']  = all_data['GarageYrBlt'].fillna(1978)

In [190]:
print('MiscVal  == 0 percent -> %3.2f%%'%(100*(all_data['MiscVal'].values == 0).sum() / all_data['MiscVal'].values.shape[0] ))
print('PoolArea == 0 percent -> %3.2f%%'%(100*(all_data['PoolArea'].values == 0).sum() / all_data['PoolArea'].values.shape[0] ))

In [192]:
all_data = all_data.drop('MiscVal', 1)
all_data = all_data.drop('PoolArea', 1)

print(all_data.isnull().sum().max())

0

In [193]:
numerical_data    = [var for var in all_data.columns if all_data.dtypes[var] != 'object']
categorical_data  = [var for var in all_data.columns if all_data.dtypes[var] == 'object']

numerical_data.remove('Id')
#numerical_data.remove('SalePrice')
print('Number of numerical data   : ', len(numerical_data))
print('Number of categorical data : ', len(categorical_data))

Number of numerical data   :  14
Number of categorical data :  38

In [194]:
all_data = pd.get_dummies(all_data, columns=categorical_data)
#encoders = []
#for i, name in enumerate(categorical_data):
    #train_data[name].get_dummies()
    #pd.get_dummies(train_data[name])
    #print(pd.get_dummies(train_data[name]).shape)
    #x = train_data[name].values
    #encoders.append(LabelEncoder())
    #label_enc = LabelEncoder()
    #x = label_enc.fit_transform(x)
    #x[:,0] = encoders[i].fit_transform(x[:,])
    #oneH_enc = OneHotEncoder(categorical_features = None)
    #encoders.append(enc)
    #x = oneH_enc.fit_transform(x).toarray()
    #train_data[name] = oneH_enc.fit_transform(x).toarray()
    #encoders.append(LabelEncoder())
    #train_data[name] = encoders[i].fit_transform(x)
#    train_data[name] = pd.get_dummies(train_data[name])
scalers  = []
#all_data = all_data.astype(np.float32)
for name in all_data:
    if name == 'Id':
        continue
    x = all_data[name].values.astype(np.float32)
    x = x.reshape(-1,1)
    scaler = StandardScaler()
    scaler.fit(x)
    #scalers.append(scaler)
    all_data[name] = scaler.transform(x)

In [195]:
all_data.head()

,Id,LotFrontage,OverallQual,OverallCond,YearRemodAdd,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,0.216075,0.646183,-0.507284,0.896833,1.087334,1.087334,0.781366,1.232599,0.169927,...,-0.052423,-0.298629,-0.052423,0.395018,-0.263861,-0.064249,-0.09105,-0.126535,0.463937,-0.302693
1,2,0.664158,-0.063185,2.188279,-0.395604,-0.818929,-0.818929,0.781366,-0.756321,0.169927,...,-0.052423,-0.298629,-0.052423,0.395018,-0.263861,-0.064249,-0.09105,-0.126535,0.463937,-0.302693
2,3,0.305692,0.646183,-0.507284,0.848965,1.087334,1.087334,0.781366,1.232599,0.169927,...,-0.052423,-0.298629,-0.052423,0.395018,-0.263861,-0.064249,-0.09105,-0.126535,0.463937,-0.302693
3,4,0.066714,0.646183,-0.507284,-0.682812,1.087334,1.087334,-1.027363,-0.756321,0.169927,...,-0.052423,-0.298629,-0.052423,0.395018,3.789876,-0.064249,-0.09105,-0.126535,-2.155466,-0.302693
4,5,0.783647,1.355551,-0.507284,0.753229,1.087334,1.087334,0.781366,1.232599,1.385655,...,-0.052423,-0.298629,-0.052423,0.395018,-0.263861,-0.064249,-0.09105,-0.126535,0.463937,-0.302693

In [196]:
train_data = all_data[:1460]
test_data = all_data[1460:]

## 4. Model

In [197]:
def getPrediction(W, b, input_data):
    return np.sum(W*input_data) + b

def RMSE(Y, pred, m):
    return np.sqrt(np.mean(np.square(np.log(Y+1)-np.log(pred+1))))

def train(input_, err, lr):
    global W, b
    W = W  + lr * err * input_
    b = b  + lr * err

## 5. Training

In [198]:
train_data_values = train_data.values

In [199]:
train_input = train_data_values[:, 1:]
#train_label = train_data_values[:,-1]
train_label_values = train_label.values
train_input = train_input.astype(np.float64)

In [202]:
n, m = train_input.shape
print('n = %d, m = %d'%(n,m))
W = np.random.normal(0.0, 0.001, m)
b = 0.0
def linear_regression(train_input, train_label):
    global W, b
    n, m    = train_input.shape
    pred_ar = np.ndarray(shape=(n,), dtype=np.float32)
    for i in range(1, 901):
        for id in range(n):
            pred = getPrediction(W, b, train_input[id])
            err  = train_label_values[id] - pred
            train(train_input[id], err, 1e-5)

        #pred_ar[pred_ar < 0] = 0
        
        if (i%50 == 0):
            pred_ar = np.matmul(train_input,W) + b
            cc = pred_ar[pred_ar < 0].sum()
            loss = RMSE(train_label_values, pred_ar, m)
            print("ep : %5d loss = %.6f, count = %d"%(i, loss, cc))

linear_regression(train_input, train_label)

n = 1460, m = 258

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in log
  """

ep :    50 loss = nan, count = -1698934
ep :   100 loss = nan, count = -157641
ep :   150 loss = nan, count = -1025
ep :   200 loss = 0.176210, count = 0
ep :   250 loss = 0.148101, count = 0
ep :   300 loss = 0.137922, count = 0
ep :   350 loss = 0.133644, count = 0
ep :   400 loss = 0.131594, count = 0
ep :   450 loss = 0.130511, count = 0
ep :   500 loss = 0.129903, count = 0
ep :   550 loss = 0.129552, count = 0
ep :   600 loss = 0.129347, count = 0
ep :   650 loss = 0.129232, count = 0
ep :   700 loss = 0.129171, count = 0
ep :   750 loss = 0.129144, count = 0
ep :   800 loss = 0.129140, count = 0
ep :   850 loss = 0.129149, count = 0
ep :   900 loss = 0.129167, count = 0

## 6. Testing

In [203]:
test_data  = all_data[1460:]
test_data.head()


test_input = test_data.values.astype(np.float64)[:,1:]
#test_input       = test_data_values[:, 1:]
test_input       = test_input.astype(np.float32)

In [204]:
train_data.head()

,Id,LotFrontage,OverallQual,OverallCond,YearRemodAdd,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,0.216075,0.646183,-0.507284,0.896833,1.087334,1.087334,0.781366,1.232599,0.169927,...,-0.052423,-0.298629,-0.052423,0.395018,-0.263861,-0.064249,-0.09105,-0.126535,0.463937,-0.302693
1,2,0.664158,-0.063185,2.188279,-0.395604,-0.818929,-0.818929,0.781366,-0.756321,0.169927,...,-0.052423,-0.298629,-0.052423,0.395018,-0.263861,-0.064249,-0.09105,-0.126535,0.463937,-0.302693
2,3,0.305692,0.646183,-0.507284,0.848965,1.087334,1.087334,0.781366,1.232599,0.169927,...,-0.052423,-0.298629,-0.052423,0.395018,-0.263861,-0.064249,-0.09105,-0.126535,0.463937,-0.302693
3,4,0.066714,0.646183,-0.507284,-0.682812,1.087334,1.087334,-1.027363,-0.756321,0.169927,...,-0.052423,-0.298629,-0.052423,0.395018,3.789876,-0.064249,-0.09105,-0.126535,-2.155466,-0.302693
4,5,0.783647,1.355551,-0.507284,0.753229,1.087334,1.087334,0.781366,1.232599,1.385655,...,-0.052423,-0.298629,-0.052423,0.395018,-0.263861,-0.064249,-0.09105,-0.126535,0.463937,-0.302693

In [205]:
n, m         = test_input.shape
pred_test_ar = np.matmul(test_input,W) + b

In [206]:
pred_pd = pd.DataFrame(pred_test_ar, columns=['SalePrice'])
out     = pd.concat([test_data['Id'],pred_pd], axis=1)
out

        Id      SalePrice
0     1461  101910.681458
1     1462  139103.651217
2     1463  160103.773905
3     1464  186975.270432
4     1465  201175.302763
5     1466  166927.197831
6     1467  169668.818425
7     1468  165651.285767
8     1469  194145.948323
9     1470  113866.972708
10    1471  155853.183734
11    1472   97763.304703
12    1473   89684.810807
13    1474  128183.363268
14    1475   78499.679668
15    1476  382118.702159
16    1477  254922.874687
17    1478  331085.468431
18    1479  331716.312881
19    1480  441954.166076
20    1481  304689.957488
21    1482  217283.516011
22    1483  157201.050622
23    1484  168717.272042
24    1485  200458.578433
25    1486  187127.548209
26    1487  343941.066705
27    1488  216166.947638
28    1489  191467.682691
29    1490  245794.174829
...    ...            ...
1429  2890   65342.368043
1430  2891  133579.839400
1431  2892   11324.280805
1432  2893   64554.233533
1433  2894   20112.226942
1434  2895  337956.536325
1435  2896  284657.207648
1436  2897  215461.359847
1437  2898  140518.798123
1438  2899  221368.642645
1439  2900  173342.002831
1440  2901  194014.165865
1441  2902  177897.195064
1442  2903  309662.487332
1443  2904  368484.443116
1444  2905   63819.691218
1445  2906  223308.261370
1446  2907  107938.445831
1447  2908  123185.610427
1448  2909  130860.241639
1449  2910   68686.423885
1450  2911   75715.962874
1451  2912  162598.603183
1452  2913   78226.820921
1453  2914   65457.243580
1454  2915   72946.850120
1455  2916   91335.963843
1456  2917  161698.623507
1457  2918   88069.465326
1458  2919  236017.229006

[1459 rows x 2 columns]

In [207]:
out.to_csv('all/regr_lin1.csv',index=False)
#tt1 = pd.read_csv('all/regr_lin.csv')

In [208]:
pd.read_csv('all/regr_lin.csv')

        Id      SalePrice
0     1461  111987.949920
1     1462  159006.541023
2     1463  181751.497798
3     1464  199622.458834
4     1465  201850.044658
5     1466  173166.025728
6     1467  174004.580737
7     1468  166031.810086
8     1469  195481.759694
9     1470  119611.517105
10    1471  176446.984240
11    1472   97128.180903
12    1473   95197.834743
13    1474  145214.909159
14    1475   98215.837455
15    1476  368528.285646
16    1477  250588.963206
17    1478  300927.100169
18    1479  311517.509513
19    1480  439529.986664
20    1481  305447.537848
21    1482  217183.192059
22    1483  175289.558990
23    1484  171330.480950
24    1485  191249.415170
25    1486  199604.114846
26    1487  345562.053230
27    1488  224242.352119
28    1489  200198.957377
29    1490  243571.129299
...    ...            ...
1429  2890   75526.148785
1430  2891  140716.036580
1431  2892   18259.151284
1432  2893   63177.252458
1433  2894   33077.850435
1434  2895  338100.856033
1435  2896  289210.158860
1436  2897  212188.371047
1437  2898  141167.421875
1438  2899  217748.347590
1439  2900  162416.845271
1440  2901  206601.075517
1441  2902  182401.102693
1442  2903  308277.494206
1443  2904  347953.606303
1444  2905   61416.176168
1445  2906  197562.630812
1446  2907  116688.658729
1447  2908  121054.924769
1448  2909  142615.423346
1449  2910   71871.077136
1450  2911   79779.707297
1451  2912  160052.903958
1452  2913   74885.987368
1453  2914   72754.248216
1454  2915   77510.172444
1455  2916   81104.345055
1456  2917  165805.944199
1457  2918  111293.841958
1458  2919  222493.709394

[1459 rows x 2 columns]