# House Prices: Advanced Regression Techniques

## 1. Getting data with Pandas

In [161]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.linear_model import ElasticNet
from sklearn.datasets import make_regression

In [162]:
train_data = pd.read_csv('all/train.csv')
test_data  = pd.read_csv('all/test.csv')

In [163]:
train_label = train_data['SalePrice']
train_data_input = train_data.drop('SalePrice',1)
all_data   = pd.concat([train_data_input, test_data], axis=0)

print(train_data.shape)
print(train_data_input.shape)
print(test_data.shape)
print(all_data.shape)

(1460, 81)
(1460, 80)
(1459, 80)
(2919, 80)

In [164]:
train_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

## 2. Data exploration

In [165]:
all_data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Shed,350,11,2009,WD,Normal
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,1,2008,WD,Normal
10,11,20,RL,70.0,11200,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
11,12,60,RL,85.0,11924,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,7,2006,New,Partial
12,13,20,RL,NaN,12968,Pave,NaN,IR2,Lvl,AllPub,...,176,0,NaN,NaN,NaN,0,9,2008,WD,Normal
13,14,20,RL,91.0,10652,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,8,2007,New,Partial
14,15,20,RL,NaN,10920,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,GdWo,NaN,0,5,2008,WD,Normal
15,16,45,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,GdPrv,NaN,0,7,2007,WD,Normal
16,17,20,RL,NaN,11241,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Shed,700,3,2010,WD,Normal
17,18,90,RL,72.0,10791,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,Shed,500,10,2006,WD,Normal
18,19,20,RL,66.0,13695,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2008,WD,Normal
19,20,20,RL,70.0,7560,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,5,2009,COD,Abnorml
20,21,60,RL,101.0,14215,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,New,Partial
21,22,45,RM,57.0,7449,Pave,Grvl,Reg,Bnk,AllPub,...,0,0,NaN,GdPrv,NaN,0,6,2007,WD,Normal
22,23,20,RL,75.0,9742,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
23,24,120,RM,44.0,4224,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2007,WD,Normal
24,25,20,RL,NaN,8246,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,5,2010,WD,Normal
25,26,20,RL,110.0,14230,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,7,2009,WD,Normal
26,27,20,RL,60.0,7200,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal
27,28,20,RL,98.0,11478,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal
28,29,20,RL,47.0,16321,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2006,WD,Normal
29,30,30,RM,60.0,6324,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2008,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,2890,30,RM,50.0,7030,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2006,WD,Normal
1430,2891,50,RM,75.0,9060,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Normal
1431,2892,30,C (all),69.0,12366,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Abnorml
1432,2893,190,C (all),50.0,9000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Abnorml
1433,2894,50,C (all),60.0,8520,Grvl,NaN,Reg,Bnk,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Normal
1434,2895,120,RM,41.0,5748,Pave,NaN,IR1,HLS,AllPub,...,153,0,NaN,NaN,NaN,0,2,2006,New,Partial
1435,2896,120,RM,44.0,3842,Pave,NaN,IR1,HLS,AllPub,...,155,0,NaN,NaN,NaN,0,12,2006,WD,Normal
1436,2897,20,RL,69.0,23580,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Normal
1437,2898,90,RL,65.0,8385,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Normal
1438,2899,20,RL,70.0,9116,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1439,2900,80,RL,140.0,11080,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1440,2901,20,RL,NaN,50102,Pave,NaN,IR1,Low,AllPub,...,138,0,NaN,NaN,NaN,0,3,2006,WD,Alloca
1441,2902,20,RL,NaN,8098,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Normal
1442,2903,20,RL,95.0,13618,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,New,Partial
1443,2904,20,RL,88.0,11577,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,New,Partial
1444,2905,20,NaN,125.0,31250,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1445,2906,90,RM,78.0,7020,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal
1446,2907,160,RM,41.0,2665,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1447,2908,20,RL,58.0,10172,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Normal
1448,2909,90,RL,NaN,11836,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,3,2006,WD,Normal
1449,2910,180,RM,21.0,1470,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Normal
1450,2911,160,RM,21.0,1484,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1451,2912,20,RL,80.0,13384,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1452,2913,160,RM,21.0,1533,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2006,WD,Abnorml
1453,2914,160,RM,21.0,1526,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,GdPrv,NaN,0,6,2006,WD,Normal
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [166]:
train_data['SalePrice'].describe()

count      1460.000000
mean     180921.195890
std       79442.502883
min       34900.000000
25%      129975.000000
50%      163000.000000
75%      214000.000000
max      755000.000000
Name: SalePrice, dtype: float64

## 3. Prepare data

In [167]:
missing_data = all_data.isnull().sum().sort_values(ascending=False)
missing_data = missing_data[missing_data > 0]

In [168]:
count        = all_data.isnull().sum().sort_values(ascending=False)
percent_relt = all_data.isnull().sum() / all_data.isnull().count()
percent_relt = percent_relt.sort_values(ascending=False)*100

missing_data_perc  = pd.concat([count, percent_relt], axis=1, keys = ['Count', 'Percent(%)'])
missing_data_perc.head(50)

              Count  Percent(%)
PoolQC         2909   99.657417
MiscFeature    2814   96.402878
Alley          2721   93.216855
Fence          2348   80.438506
FireplaceQu    1420   48.646797
LotFrontage     486   16.649538
GarageCond      159    5.447071
GarageQual      159    5.447071
GarageYrBlt     159    5.447071
GarageFinish    159    5.447071
GarageType      157    5.378554
BsmtCond         82    2.809181
BsmtExposure     82    2.809181
BsmtQual         81    2.774923
BsmtFinType2     80    2.740665
BsmtFinType1     79    2.706406
MasVnrType       24    0.822199
MasVnrArea       23    0.787941
MSZoning          4    0.137033
BsmtHalfBath      2    0.068517
Utilities         2    0.068517
Functional        2    0.068517
BsmtFullBath      2    0.068517
BsmtFinSF1        1    0.034258
Exterior1st       1    0.034258
Exterior2nd       1    0.034258
BsmtFinSF2        1    0.034258
BsmtUnfSF         1    0.034258
TotalBsmtSF       1    0.034258
SaleType          1    0.034258
Electrical        1    0.034258
KitchenQual       1    0.034258
GarageArea        1    0.034258
GarageCars        1    0.034258
HouseStyle        0    0.000000
LandSlope         0    0.000000
MSSubClass        0    0.000000
LotArea           0    0.000000
Street            0    0.000000
LotShape          0    0.000000
LandContour       0    0.000000
LotConfig         0    0.000000
Neighborhood      0    0.000000
OverallQual       0    0.000000
Condition1        0    0.000000
Condition2        0    0.000000
RoofMatl          0    0.000000
RoofStyle         0    0.000000
BldgType          0    0.000000
YearRemodAdd      0    0.000000

In [169]:
all_data = all_data.drop((missing_data_perc[missing_data_perc['Percent(%)'] > 25]).index, 1)

all_data = all_data.drop('LotArea', 1)
all_data = all_data.drop('YearBuilt', 1)
all_data = all_data.drop('BsmtFinSF1', 1)
#all_data = all_data.drop('MasVnrArea', 1)

In [170]:
#all_data['FireplaceQu']  = all_data['FireplaceQu'].fillna('NA')

#all_data['LotArea']  = all_data['LotArea'].fillna(0)

all_data['LotFrontage']  = all_data['LotFrontage'].fillna(0)
all_data['GarageCond']   = all_data['GarageCond'].fillna('NA')
all_data['GarageType']   = all_data['GarageType'].fillna('NA')
all_data['GarageFinish'] = all_data['GarageFinish'].fillna('NA')
all_data['GarageQual']   = all_data['GarageQual'].fillna('NA')
all_data['BsmtExposure'] = all_data['BsmtExposure'].fillna('NA')
all_data['BsmtFinType2'] = all_data['BsmtFinType2'].fillna('NA')
all_data['BsmtFinType1'] = all_data['BsmtFinType1'].fillna('NA')
all_data['BsmtCond']     = all_data['BsmtCond'].fillna('NA')
all_data['BsmtQual']     = all_data['BsmtQual'].fillna('NA')
all_data['MasVnrArea']   = all_data['MasVnrArea'].fillna(0)
all_data['MasVnrType']   = all_data['MasVnrType'].fillna('None')
all_data['Electrical']   = all_data['Electrical'].fillna('SBrkr')
all_data['MSZoning']     = all_data['MSZoning'].fillna('RM')
all_data['Functional']   = all_data['Functional'].fillna('Typ')
all_data['BsmtFullBath'] = all_data['BsmtFullBath'].fillna(0)
all_data['BsmtHalfBath'] = all_data['BsmtFullBath'].fillna(0)
all_data['Utilities']    = all_data['Utilities'].fillna('AllPub')
all_data['GarageArea']   = all_data['GarageArea'].fillna(0)
all_data['BsmtFinSF2']   = all_data['BsmtFinSF2'].fillna(0)
all_data['BsmtUnfSF']    = all_data['BsmtUnfSF'].fillna(0)
all_data['SaleType']     = all_data['SaleType'].fillna('Oth')
all_data['Exterior2nd']  = all_data['Exterior2nd'].fillna('Other')
all_data['Exterior1st']  = all_data['Exterior1st'].fillna('Other')
all_data['KitchenQual']  = all_data['KitchenQual'].fillna('TA')
all_data['GarageCars']   = all_data['GarageCars'].fillna(0)
all_data['TotalBsmtSF']  = all_data['TotalBsmtSF'].fillna(0)

In [171]:
all_data['GarageYrBlt'].describe()
all_data['GarageYrBlt']  = all_data['GarageYrBlt'].fillna(1978)

In [172]:
print('MiscVal  == 0 percent -> %3.2f%%'%(100*(all_data['MiscVal'].values == 0).sum() / all_data['MiscVal'].values.shape[0] ))
print('PoolArea == 0 percent -> %3.2f%%'%(100*(all_data['PoolArea'].values == 0).sum() / all_data['PoolArea'].values.shape[0] ))

MiscVal  == 0 percent -> 96.47%
PoolArea == 0 percent -> 99.55%

In [173]:
all_data = all_data.drop('MiscVal', 1)
all_data = all_data.drop('PoolArea', 1)

print(all_data.isnull().sum().max())

0

In [174]:
numerical_data    = [var for var in all_data.columns if all_data.dtypes[var] != 'object']
categorical_data  = [var for var in all_data.columns if all_data.dtypes[var] == 'object']

numerical_data.remove('Id')
#numerical_data.remove('SalePrice')
print('Number of numerical data   : ', len(numerical_data))
print('Number of categorical data : ', len(categorical_data))

Number of numerical data   :  31
Number of categorical data :  38

In [175]:
all_data = pd.get_dummies(all_data, columns=categorical_data)
scalers  = []
#all_data = all_data.astype(np.float32)
for name in all_data:
    if name == 'Id':
        continue
    x = all_data[name].values.astype(np.float32)
    x = x.reshape(-1,1)
    scaler = StandardScaler()
    scaler.fit(x)
    #scalers.append(scaler)
    all_data[name] = scaler.transform(x)

In [176]:
all_data.head()

,Id,MSSubClass,LotFrontage,OverallQual,OverallCond,YearRemodAdd,MasVnrArea,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,0.067331,0.216075,0.646183,-0.507284,0.896833,0.529034,-0.293025,-0.934165,-0.443078,...,-0.052423,-0.298629,-0.052423,0.395018,-0.263861,-0.064249,-0.09105,-0.126535,0.463937,-0.302693
1,2,-0.873616,0.664158,-0.063185,2.188279,-0.395604,-0.567016,-0.293025,-0.629284,0.477463,...,-0.052423,-0.298629,-0.052423,0.395018,-0.263861,-0.064249,-0.09105,-0.126535,0.463937,-0.302693
2,3,0.067331,0.305692,0.646183,-0.507284,0.848965,0.338903,-0.293025,-0.287999,-0.297968,...,-0.052423,-0.298629,-0.052423,0.395018,-0.263861,-0.064249,-0.09105,-0.126535,0.463937,-0.302693
3,4,0.302568,0.066714,0.646183,-0.507284,-0.682812,-0.567016,-0.293025,-0.046824,-0.669812,...,-0.052423,-0.298629,-0.052423,0.395018,3.789876,-0.064249,-0.09105,-0.126535,-2.155466,-0.302693
4,5,0.067331,0.783647,1.355551,-0.507284,0.753229,1.390216,-0.293025,-0.160586,0.212184,...,-0.052423,-0.298629,-0.052423,0.395018,-0.263861,-0.064249,-0.09105,-0.126535,0.463937,-0.302693

In [177]:
train_data = all_data[:1460]
test_data = all_data[1460:]

## 4. Model

In [178]:
def getPrediction(W, b, input_data):
    return np.sum(W*input_data) + b

def RMSE(Y, pred, m):
    return np.sqrt(np.mean(np.square(np.log(Y+1)-np.log(pred+1))))

def train(input_, err, lr):
    global W, b
    W = W  + lr * err * input_
    b = b  + lr * err

## 5. Training

In [179]:
train_data_values = train_data.values

In [180]:
train_input = train_data_values[:, 1:]
#train_label = train_data_values[:,-1]
train_label_values = train_label.values
train_input = train_input.astype(np.float64)

In [181]:
n, m = train_input.shape
regr = ElasticNet(random_state=0, max_iter = 1000)
regr.fit(train_input, train_label)

ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=0, selection='cyclic', tol=0.0001, warm_start=False)

In [182]:
pred_ar = regr.predict(train_input)
RMSE(train_label, pred_ar, m)

0.11566551457771446

## 6. Testing

In [183]:
test_data  = all_data[1460:]
test_data.head()


test_input = test_data.values.astype(np.float64)[:,1:]
#test_input       = test_data_values[:, 1:]
test_input       = test_input.astype(np.float32)

In [184]:
train_data.head()

,Id,MSSubClass,LotFrontage,OverallQual,OverallCond,YearRemodAdd,MasVnrArea,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,0.067331,0.216075,0.646183,-0.507284,0.896833,0.529034,-0.293025,-0.934165,-0.443078,...,-0.052423,-0.298629,-0.052423,0.395018,-0.263861,-0.064249,-0.09105,-0.126535,0.463937,-0.302693
1,2,-0.873616,0.664158,-0.063185,2.188279,-0.395604,-0.567016,-0.293025,-0.629284,0.477463,...,-0.052423,-0.298629,-0.052423,0.395018,-0.263861,-0.064249,-0.09105,-0.126535,0.463937,-0.302693
2,3,0.067331,0.305692,0.646183,-0.507284,0.848965,0.338903,-0.293025,-0.287999,-0.297968,...,-0.052423,-0.298629,-0.052423,0.395018,-0.263861,-0.064249,-0.09105,-0.126535,0.463937,-0.302693
3,4,0.302568,0.066714,0.646183,-0.507284,-0.682812,-0.567016,-0.293025,-0.046824,-0.669812,...,-0.052423,-0.298629,-0.052423,0.395018,3.789876,-0.064249,-0.09105,-0.126535,-2.155466,-0.302693
4,5,0.067331,0.783647,1.355551,-0.507284,0.753229,1.390216,-0.293025,-0.160586,0.212184,...,-0.052423,-0.298629,-0.052423,0.395018,-0.263861,-0.064249,-0.09105,-0.126535,0.463937,-0.302693

In [185]:
n, m         = test_input.shape
pred_test_ar = regr.predict(test_input)
#pred_test_ar = np.matmul(test_input,W) + b

In [186]:
pred_pd = pd.DataFrame(pred_test_ar, columns=['SalePrice'])
out     = pd.concat([test_data['Id'],pred_pd], axis=1)
out

        Id      SalePrice
0     1461  111072.848847
1     1462  156790.287009
2     1463  181029.518510
3     1464  195958.250441
4     1465  201018.939576
5     1466  172799.459511
6     1467  174251.007037
7     1468  165869.002042
8     1469  194903.167467
9     1470  119415.502217
10    1471  175413.257451
11    1472  101254.346500
12    1473   99274.404104
13    1474  144944.613874
14    1475   99589.147251
15    1476  364039.265739
16    1477  251775.876402
17    1478  306673.245398
18    1479  310380.936011
19    1480  451652.041734
20    1481  303567.362266
21    1482  216820.007089
22    1483  175608.081444
23    1484  170365.000715
24    1485  191357.546982
25    1486  199202.292129
26    1487  338137.687606
27    1488  224095.403815
28    1489  198713.422320
29    1490  241578.547473
...    ...            ...
1429  2890   75819.514503
1430  2891  143287.007609
1431  2892   19041.082059
1432  2893   63576.332145
1433  2894   34071.121340
1434  2895  342911.610524
1435  2896  288461.227404
1436  2897  210365.013749
1437  2898  141170.281135
1438  2899  216220.683402
1439  2900  163829.984423
1440  2901  205135.304781
1441  2902  183177.327060
1442  2903  308627.975997
1443  2904  348796.507792
1444  2905   61566.114967
1445  2906  196962.216103
1446  2907  116628.935706
1447  2908  121883.120632
1448  2909  141845.271003
1449  2910   72348.320573
1450  2911   79271.127539
1451  2912  160213.370335
1452  2913   75503.261002
1453  2914   72750.782924
1454  2915   77572.531660
1455  2916   81423.805949
1456  2917  165337.999534
1457  2918  111534.635019
1458  2919  219444.822687

[1459 rows x 2 columns]

In [187]:
out.to_csv('all/elastic_net.csv',index=False)
tt1 = pd.read_csv('all/elastic_net.csv')

In [150]:
tt1

        Id      SalePrice
0     1461  113085.739782
1     1462  158183.857596
2     1463  182935.534984
3     1464  196396.220594
4     1465  200543.871974
5     1466  172425.328542
6     1467  172891.064887
7     1468  165414.766769
8     1469  194629.676856
9     1470  117489.481587
10    1471  174141.433321
11    1472  100931.848826
12    1473   99103.059953
13    1474  143903.514766
14    1475   99467.233095
15    1476  364339.044276
16    1477  252581.717039
17    1478  308187.860417
18    1479  312082.587190
19    1480  449464.836005
20    1481  303424.588027
21    1482  217020.527312
22    1483  179053.714824
23    1484  170699.926843
24    1485  193751.892879
25    1486  198827.313167
26    1487  337662.986239
27    1488  223266.289262
28    1489  199309.769251
29    1490  242430.749692
...    ...            ...
1429  2890   77084.743189
1430  2891  143579.815249
1431  2892   23110.975710
1432  2893   66313.573340
1433  2894   28289.306867
1434  2895  340709.806753
1435  2896  286078.985029
1436  2897  214044.402556
1437  2898  139968.622141
1438  2899  215696.784544
1439  2900  163504.509781
1440  2901  215628.943245
1441  2902  180862.492418
1442  2903  307288.403829
1443  2904  345621.497726
1444  2905   70496.345719
1445  2906  195865.842640
1446  2907  116505.507840
1447  2908  121669.051915
1448  2909  141930.678585
1449  2910   72592.495739
1450  2911   78862.522465
1451  2912  159996.845974
1452  2913   75929.920041
1453  2914   72860.664985
1454  2915   77957.244788
1455  2916   81761.528832
1456  2917  168556.467660
1457  2918  113479.640234
1458  2919  219092.083550

[1459 rows x 2 columns]